ARG LINKERD_AWAIT_VERSION=v0.1.2
FROM olix0r/linkerd-await:v0.1.1 as await

FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y iperf && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/
