ARG RUST_IMAGE=rust:1.41.0-buster
ARG RUSTFLAGS="-C debuginfo=2 -C lto=off"
ARG RUNTIME_IMAGE=debian:bullseye-slim

FROM $RUST_IMAGE as build
WORKDIR /usr/src/linkerd2-proxy
COPY . .
RUN cargo fetch --locked
RUN RUSTFLAGS=$RUSTFLAGS cargo build \
    --frozen --release \
    -p linkerd2-app-profiling \
    --bin profile

## Install the proxy binary into the base runtime image.
FROM $RUNTIME_IMAGE as runtime
RUN apt-get update && \
    apt-get install -y linux-base netcat curl iproute2 && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/ && \
COPY --from=build /usr/src/linkerd2-proxy/target/release/profile /usr/bin/linkerd2-proxy-profiler
ENV PATH="/usr/bin/:${PATH}"
ENTRYPOINT ["/usr/bin/linkerd2-proxy"]
